# Generated by Django 3.1.2 on 2020-11-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thepartofspeech',
            options={'verbose_name': '词性表', 'verbose_name_plural': '词性表'},
        ),
        migrations.AlterModelTable(
            name='thepartofspeech',
            table='ThePartOfSpeech',
        ),
    ]
