# Generated by Django 3.1.2 on 2020-11-02 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_auto_20201102_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_part_of_speech', models.CharField(choices=[('名词', 'n.'), ('可数名词', 'c.'), ('不可数名词', 'u.'), ('动词', 'v.'), ('及物动词', 'vt.'), ('不及物动词', 'vi.'), ('副词', 'adv.'), ('助动词', 'aux.v'), ('形容词', 'adj.'), ('冠词', 'art.'), ('感叹词', 'int.'), ('受词', 'o.'), ('受词补语', 'oc.'), ('主词', 's.'), ('主词补语', 'sc.'), ('介系词', 'prep.'), ('代名词', 'pron')], max_length=10, verbose_name='词性')),
                ('translation', models.CharField(max_length=20, verbose_name='释义')),
            ],
            options={
                'verbose_name': '翻译表',
                'verbose_name_plural': '翻译表',
                'db_table': 'Translation',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30, verbose_name='单词')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='记录日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '单词',
                'verbose_name_plural': '单词',
                'db_table': 'word',
            },
        ),
        migrations.DeleteModel(
            name='ThePartOfSpeech',
        ),
        migrations.AddField(
            model_name='translation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.word', verbose_name='单词'),
        ),
    ]
