# Generated by Django 3.1.2 on 2020-11-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_dailylog_userextension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={'verbose_name': '用户记录日志表', 'verbose_name_plural': '用户记录日志表'},
        ),
        migrations.AlterModelOptions(
            name='userextension',
            options={'verbose_name': '用户信息扩展表', 'verbose_name_plural': '用户信息扩展表'},
        ),
        migrations.AlterModelTable(
            name='dailylog',
            table='DailyLog',
        ),
        migrations.AlterModelTable(
            name='userextension',
            table='UserExtension',
        ),
    ]
