# Generated by Django 3.1.2 on 2020-11-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0005_auto_20201104_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='the_part_of_speech',
            field=models.CharField(choices=[('1', 'n.'), ('2', 'c.'), ('3', 'u.'), ('4', 'v.'), ('5', 'vt.'), ('6', 'vi.'), ('7', 'adv.'), ('8', 'aux.v'), ('9', 'adj.'), ('10', 'art.'), ('11', 'int.'), ('12', 'o.'), ('13', 'oc.'), ('14', 's.'), ('15', 'sc.'), ('16', 'prep.'), ('17', 'pron')], max_length=10, verbose_name='词性'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media/user_avatar/%Y/%m/%d', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='constellation',
            field=models.CharField(blank=True, choices=[('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius'), ('Capricorn', 'Capricorn'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces')], max_length=20, verbose_name='星座'),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='sex',
            field=models.CharField(default='男', max_length=10, verbose_name='性别'),
        ),
    ]
