# Generated by Django 3.1.2 on 2020-11-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0006_auto_20201109_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='translation',
            field=models.CharField(max_length=50, verbose_name='释义'),
        ),
    ]
